// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7SskqZ7fua8BdgcZN5GbKCt_r0zRis3g',
    appId: '1:393969785546:web:6981b46ee5c8ec868b3233',
    messagingSenderId: '393969785546',
    projectId: 'dogmatch-d1333',
    authDomain: 'dogmatch-d1333.firebaseapp.com',
    storageBucket: 'dogmatch-d1333.appspot.com',
    measurementId: 'G-BL741B9G74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTdkOu-sTWRgjW5VgGGeKMDtDwsncm4g',
    appId: '1:393969785546:android:a430e781f02348d58b3233',
    messagingSenderId: '393969785546',
    projectId: 'dogmatch-d1333',
    storageBucket: 'dogmatch-d1333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQWmuLrWEPx6eqllZXhS7hcFc7JZzcz0',
    appId: '1:393969785546:ios:fc56bb56c9ab9ce38b3233',
    messagingSenderId: '393969785546',
    projectId: 'dogmatch-d1333',
    storageBucket: 'dogmatch-d1333.appspot.com',
    iosBundleId: 'com.example.pawfect',
  );
}
