// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAngq3HRt7FwAR5t3jhhwQdTDIKUPozM84',
    appId: '1:764757429583:web:a654ce490200624306093a',
    messagingSenderId: '764757429583',
    projectId: 'dogmatch-d3595',
    authDomain: 'dogmatch-d3595.firebaseapp.com',
    storageBucket: 'dogmatch-d3595.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdbwxqgXpvibLVBZoOTprMsr1wgx57k4',
    appId: '1:764757429583:android:0af3223be4f94d8206093a',
    messagingSenderId: '764757429583',
    projectId: 'dogmatch-d3595',
    storageBucket: 'dogmatch-d3595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSaaK5TvF6WkzVw4Jm97ovV4PYEi52tc',
    appId: '1:764757429583:ios:4409abb827a5297e06093a',
    messagingSenderId: '764757429583',
    projectId: 'dogmatch-d3595',
    storageBucket: 'dogmatch-d3595.appspot.com',
    iosBundleId: 'com.example.pawfect',
  );

}