name: DogMatch
description: "A Dog friendly App"
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  animated_text_kit: ^4.2.2
  get: ^4.6.6
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.0
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  flutter_card_swiper: ^7.0.1
  carousel_slider: ^4.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  web: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/svg/
    - assets/icons/gif/
    - assets/logo.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
